version: '3.8'

services:
  app:
    build: .
    container_name: blackboxai-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - blackboxai-network

networks:
  blackboxai-network:
    driver: bridge
